### ISSUE TITLE
Nearly identical labels

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [dahlia/sider#15]
I noticed that there are two nearly identical labels:
- http://sideeffects.embl.de/labels/prescription/20091215_fcd4cf8a-e3e6-7da9-6355-c60b7400291a/C0018681/
- http://sideeffects.embl.de/labels/prescription/20061020_2dcdd1c3-6728-45fb-97aa-de21f1f5ccad/C0018681/

which happen to differ in a critical way:

![image](https://cloud.githubusercontent.com/assets/15331/15706541/21a7e95e-282f-11e6-91cb-edf7b691b0cc.png)

![image](https://cloud.githubusercontent.com/assets/15331/15706547/2b4983b4-282f-11e6-8ded-bf103b5f99ae.png)

6% vs 63% for headache when using the patch, which [results](http://sideeffects.embl.de/drugs/4510/?labels=all) in:

![image](https://cloud.githubusercontent.com/assets/15331/15706832/8dd30432-2830-11e6-973d-1d2f571f8ffd.png)

**Comment by dahlia** [comment]
I think you must find the wrong project to file this issue.

**Comment by Franck-Dernoncourt** [comment]
Whoops, sorry! (intended to post it in another GitHub repo with the same name)
